In [1]:
import numpy as np
# import sklearn as sk
from numpy import linalg as la

In [2]:
data = np.random.rand(100, 2)

In [4]:
data

array([[0.40624072, 0.36157018],
       [0.44517416, 0.84885675],
       [0.9840554 , 0.47197569],
       [0.63695946, 0.28543712],
       [0.02232263, 0.48130204],
       [0.29341742, 0.56906829],
       [0.65467457, 0.84203599],
       [0.80749051, 0.23016233],
       [0.73543419, 0.95006541],
       [0.07520938, 0.9910182 ],
       [0.71811712, 0.05654421],
       [0.80696126, 0.32270574],
       [0.62403633, 0.19762559],
       [0.9076555 , 0.88523092],
       [0.61369315, 0.08887187],
       [0.32017506, 0.59022899],
       [0.30251324, 0.13250365],
       [0.33336624, 0.62059576],
       [0.73435751, 0.5869324 ],
       [0.62653194, 0.64343191],
       [0.276314  , 0.71086412],
       [0.56806045, 0.65076175],
       [0.19587104, 0.89667614],
       [0.81034874, 0.13465197],
       [0.05772319, 0.4724931 ],
       [0.43726143, 0.31886844],
       [0.98799053, 0.2072454 ],
       [0.15083976, 0.31480636],
       [0.52392678, 0.91871703],
       [0.70324911, 0.74051196],
       [0.

In [6]:
class FuzzyCMeans():
    def __init__(self, n_clusters, m = 2, max_iter = 100, tolerance = 1e-5):
        self.n_clusters = n_clusters
        self.max_iter = max_iter
        self.tolerance = tolerance
        self.m = m

    def initialize_membership(self, data_size):
        membership = np.random.rand(data_size, self.n_clusters) # to assign random membership
        membership = membership/np.sum(membership, axis=1)[:, np.newaxis]
        print(f'Mean : {membership}')
        print(f'Shape : {membership.shape}')
        return membership
    
    def calc_clus_centroids(self, data, membership):
        um = membership**self.m
        print("\n \n Shape of UM:", um.shape, "\n \n")
        denominator = um.sum(axis = 0)
        clus_centre = np.dot(data.T, um)/denominator
        print()
        print(f'Cluster Centres : {clus_centre}')
        print()
        return clus_centre
        

    def cal_membership(self, data, clus_centre):
        dist = la.norm(data[:, np.newaxis] - clus_centre.T, axis=2)  # distance from each cluster point
        dist = np.fmax(dist, np.finfo(dist.dtype).eps)
        powered_dist = dist**(-2/(self.m -1))
        membership = powered_dist/powered_dist.sum(axis=1)[:, np.newaxis]
        return membership
    
    def campute_obj_func(self, data, clus_centre, membership):
        up = membership**self.m
        dist = la.norm(data[:, np.newaxis] - clus_centre.T, axis=2)
        obj = np.sum(up*dist**2)
        return obj
    
    def fit(self, data):
        self.membership = self.initialize_membership(data.shape[0])
        for _ in range(self.max_iter):
            old_membership = np.copy(self.membership)
            self.clus_centre = self.calc_clus_centroids(data, self.membership)
            self.membership = self.cal_membership(data, self.clus_centre)
            if la.norm(self.membership - old_membership)<self.tolerance:
                break

        self.obj_fun = self.campute_obj_func(data, self.clus_centre, self.membership)
        
    # def predict(self, data):
        # predict the probability of input belonging to each cluster         



In [7]:
FCM = FuzzyCMeans(3)

In [8]:
FCM.fit(data)

Mean : [[0.27875598 0.4834069  0.23783712]
 [0.51437654 0.34317237 0.14245109]
 [0.31095195 0.42802679 0.26102126]
 [0.45924708 0.49194224 0.04881068]
 [0.20272796 0.00874862 0.78852342]
 [0.21390588 0.09402554 0.69206858]
 [0.26139035 0.63672778 0.10188187]
 [0.39631555 0.30075543 0.30292902]
 [0.2223618  0.51368663 0.26395157]
 [0.31182029 0.17384095 0.51433876]
 [0.36250388 0.09887613 0.53862   ]
 [0.14209569 0.80554802 0.05235628]
 [0.15638686 0.27420803 0.56940511]
 [0.52140277 0.23672891 0.24186833]
 [0.29007611 0.18558685 0.52433704]
 [0.22236193 0.41935932 0.35827874]
 [0.52788173 0.44728183 0.02483644]
 [0.68299745 0.22835931 0.08864324]
 [0.42912826 0.39361747 0.17725427]
 [0.22820384 0.33687507 0.43492108]
 [0.43977911 0.17363594 0.38658495]
 [0.20224358 0.57050382 0.2272526 ]
 [0.56056094 0.435899   0.00354006]
 [0.05311295 0.49680564 0.45008141]
 [0.37436942 0.35574307 0.2698875 ]
 [0.18326072 0.38814495 0.42859433]
 [0.19109843 0.53059132 0.27831024]
 [0.1549952  0.635188